name: Deploy React App
on: 
  push:
    branches:
      - master
    # paths-ignore:
    #   - '.github/workflows/*'
jobs:
  test_my_comp: 
    runs-on: ubuntu-latest
    steps: 
    - name: Get the repository code
      #run: echo
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Test application
      run: npm run test
  lint: 
    runs-on: ubuntu-latest
    steps: 
    - name: Get the repository code
      uses: actions/checkout@v3
    - name: Cache deps
      uses: actions/cache@v3
      with: 
        path: ~/.npm
        key: node-modules-${{hashFiles('**/package-lock.json')}}
    - name: Install dependencies
      run: npm ci
    - name: Lint application
      run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: [lint, test_my_comp]
    steps: 
    - name: Get the repository code
      uses: actions/checkout@v3
    - name: Cache deps
      uses: actions/cache@v3
      with: 
        path: ~/.npm
        key: node-modules-${{hashFiles('**/package-lock.json')}}
    - name: Install dependencies
      run: npm ci
    - name: Build application
      run: npm run build
    - name: Deploy
      run: echo Deploying....
